spring:
  application:
    name: matching-engine

  profiles:
    active: dev

server:
  port: 8080

  tomcat:
    threads:
      max: 50
      min-spare: 10

    accept-count: 100
    max-connections: 10000
    connection-timeout: 20000

management:
  endpoints:
    web:
      exposure:
        #include: health,metrics,prometheus,info,threaddump
        include: "*"
      #base-path: /actuator
  metrics:
    distribution:
      perncentiles-histogram:
        orden:
          tiempo:
            total: true
      percentiles:
        orden:
          tiempo-total: 0.95
  endpoint:
    health:
      show-details: always
    metrics:
      enable: true

 # metrics:
 #   export:
  #    prometheus:
  #      enabled: true
  #management.endpoints.web.exposure.include=*
  #management.endpoint.metrics.enabled=true
  #management.metrics.distribution.percentiles-histogram.orden.tiempo.total=true
  #management.metrics.distribution.percentiles.orden_tiempo_total=0.95

logging:
  level:
    root: INFO
    com.uniandes.matching: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

workers:
  notifications:
    count: 10
    queue-capacity: 1000

  persistence:
    sales:
      count: 8
      queue-capacity: 1000
    buys:
      count: 12
      queue-capacity: 1000